### ISSUE TITLE
Interpretation of max_len in graph sampling

### ISSUE THREAD

**Issue by n-kish** [recursionpharma/gflownet#140]
Hi, 

Thanks for the great work! 

I am going through the sEH_frag task, and am confused by the 'max_len' parameter. 

My intuition is the sampler (at least initially) should be able to sample across all possible graphs (ie. different total nodes). However, when I run the code in a purely online setting with offline_ratio=0, graphs of length equal to max_len are the only ones being sampled initially. 

I tested and observed that the sampler is capable of producing graphs that are smaller than max_len (if mandated by the reward function) but only after a majority of samples around max_len.

Is this expected behavior or are there tunable parameters that can help me produce graphs of different node lengths in the first few batches?

**Comment by bengioe** [comment]
Hi, this is somewhat expected behavior if the reward doesn't penalize large objects.

One way to think about it is that if there are 1000 actions, then there are (roughly) 1000 times more objects of size n+1 than of size n. If the reward is mostly independent of size, then the correct reward-proportional sampling policy should sample objects of size n+1 1000 times more often than objects of size n. This of course compounds exponentially. 

Typical strategies to mitigate this are to penalize size, or to "early stop" trajectories with some probability (this is something we've done in the past but is not implemented here; although it should be easy to add to [`GraphSampler`](https://github.com/recursionpharma/gflownet/blob/trunk/src/gflownet/algo/graph_sampling.py)).
